import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "./theme-provider";
import { RouteListener } from "./route-listener";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cmyk">
      <body className={inter.className}>
        <RouteListener>
          <ThemeProvider>{children}</ThemeProvider>
        </RouteListener>
      </body>
    </html>
  );
}
